
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNodW9uZ3RyaEBnbWFpbC5jb20iLCJpc19hZG1pbiI6dHJ1ZSwiaWQiOiJ1TTR2N3VzZHFCZmhqTW1tbERCUSIsImlzcyI6InBva3BvayIsImV4cCI6MTY3ODUzMDU3MH0.yIBfxhPZJ4IB3eQ60DDA4spX5PpSs6qgu2sHj2eQ6VA

### Create game

POSt http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game
Content-Type: application/json

{
    "stack":500,
    "rate":50000,
    "name":"game 01",
    "type":"texas_holdem",
    "players": [
        {
            "id":"4Mkq1W4885Byli27JdpT",
            "name":"aaa"
        },
        {
            "id":"XdgLtQD0FUsgpxXcMRyQ",
            "name":"bbb"
        }
    ]
}


###
GET http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game


###
GET http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U


### get players in game
GET  http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/player
Authorization: Bearer {{token}}

###
POST  http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/player
Content-Type: application/json

{
    "id":"4Mkq1W4885Byli27JdpT",
    "name":"aaa"
}


###
POST  http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/player
Content-Type: application/json

{
    "id":"XdgLtQD0FUsgpxXcMRyQ",
    "name":"bbb"
}

### start game
PUT http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/start
Authorization: Bearer {{token}}



### end game
PUT http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/end
Authorization: Bearer {{token}}


### action
PUT http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/action

{
    "player_id":"XdgLtQD0FUsgpxXcMRyQ",
    "action":"buyin",
    "value":1
}


### action
PUT http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/action

{
    "player_id":"4Mkq1W4885Byli27JdpT",
    "action":"buyin",
    "value":1
}


### action 
PUT http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/action

{
    "player_id":"4Mkq1W4885Byli27JdpT",
    "action":"cashout",
    "value":100
}



### get logs in game
GET  http://localhost:5200/api/clan/4sFoft7LOJP2geTPJLnN/game/b1GGQH4U37dXTJykzl1U/log

