
### get me
GET  http://localhost:5200/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNodW9uZ3RyaEBnbWFpbC5jb20iLCJpc19hZG1pbiI6dHJ1ZSwiaWQiOiJ1TTR2N3VzZHFCZmhqTW1tbERCUSIsImlzcyI6InBva3BvayIsImV4cCI6MTY3ODUzMDU3MH0.yIBfxhPZJ4IB3eQ60DDA4spX5PpSs6qgu2sHj2eQ6VA